language: generic 
sudo: required
servives:
  - docker

#Install the forntend application to test it
before install:
  - docker build -t jsrfntd/react-test -f ./client/Dockerfile.dev ./client

#Test the front ent application
script:
  - docker run -e CI=true jsrfntd/react-test npm test

after_success:
  - docker build -t jsrfntd/multi-client ./client
  - docker build -t jsrfntd/multi-nginx ./nginx
  - docker build -t jsrfntd/multi-server ./server
  - docker build -t jsrfntd/multi-worker ./worker

  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images 
  - docker push jsrfntd/multi-client
  - docker push jsrfntd/multi-nginx
  - docker push jsrfntd/multi-server
  - docker push jsrfntd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-293633716979
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    